In [1]:
.libPaths()

[1] "/Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library"

In [3]:
myString <- "Hello, World!"
print ( myString)

[1] "Hello, World!"


In [4]:

if(FALSE) {
   "This is a demo for multi-line comments and it should be put inside either a single
      of double quote"
}

myString <- "Hello, World!"
print ( myString)

[1] "Hello, World!"


In [5]:
v <- charToRaw("Hello")
print(class(v))

[1] "raw"


In [6]:
# Create a vector.
apple <- c('red','green',"yellow") #need c function to combine elements into a vector
print(apple)

# Get the class of the vector.
print(class(apple))

[1] "red"    "green"  "yellow"
[1] "character"


In [7]:
# Create a list. contain many different elements and data types
list1 <- list(c(2,5,3),21.3,sin) #vector inside list

# Print the list.
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")



In [8]:
# Create a matrix. 2d rectangular dataset; can be made with matrix function and vectors
M = matrix( c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,] "a"  "a"  "b" 
[2,] "c"  "b"  "a" 


In [9]:
# Create an array. of any number of dimensions; dim creates required dimensions
a <- array(c('green','yellow'),dim = c(3,3,2)) #3x3 matrices each (2 matrices)
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



## Factors
Factors are the r-objects which are created using a vector. It stores the vector along with the distinct values of the elements in the vector as labels. The labels are always character irrespective of whether it is numeric or character or Boolean etc. in the input vector. They are useful in statistical modeling.

Factors are created using the factor() function.The nlevels functions gives the count of levels.

In [10]:
# Create a vector.
apple_colors <- c('green','green','yellow','red','red','red','green')

# Create a factor object.
factor_apple <- factor(apple_colors)

# Print the factor.
print(factor_apple)
print(nlevels(factor_apple)

ERROR: Error in parse(text = x, srcfile = src): <text>:10:0: unexpected end of input
8: print(factor_apple)
9: print(nlevels(factor_apple)
  ^


## Data Frames
Data frames are tabular data objects. Unlike a matrix in data frame each column can contain different modes of data. The first column can be numeric while the second column can be character and third column can be logical. It is a list of vectors of equal length.

Data Frames are created using the data.frame() function.

In [20]:
# Create the data frame.
BMI <- data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)
print(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


## Variable Assignment
The variables can be assigned values using leftward, rightward and equal to operator. The values of the variables can be printed using print() or cat()function. The cat() function combines multiple items into a continuous print output.

In [12]:
# Assignment using equal operator.
var.1 = c(0,1,2,3)           

# Assignment using leftward operator.
var.2 <- c("learn","R")   

# Assignment using rightward operator.   
c(TRUE,1) -> var.3           

print(var.1)
cat ("var.1 is ", var.1 ,"\n")
cat ("var.2 is ", var.2 ,"\n")
cat ("var.3 is ", var.3 ,"\n")

[1] 0 1 2 3
var.1 is  0 1 2 3 
var.2 is  learn R 
var.3 is  1 1 


In [14]:
print(ls()) #finds all var used so far

 [1] "BMI"      "M"        "a"        "apple"    "list1"    "myString"
 [7] "v"        "var.1"    "var.2"    "var.3"   


In [16]:
# List the variables starting with the pattern "var".
print(ls(pattern = "var"))

[1] "var.1" "var.2" "var.3"


In [17]:
print(ls(all.name = TRUE))

 [1] ".pbd_env" "BMI"      "M"        "a"        "apple"    "list1"   
 [7] "myString" "v"        "var.1"    "var.2"    "var.3"   


In [19]:
#deleting vars 
rm(var.3) print(var.3) #deleted var.3 therefore cannot print

ERROR: Error in parse(text = x, srcfile = src): <text>:2:11: unexpected symbol
1: #deleting vars 
2: rm(var.3) print
             ^


In [21]:
installed.packages()

Package      LibPath                                              
BH           BH           /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
DBI          DBI          /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
IRdisplay    IRdisplay    /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
IRkernel     IRkernel     /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
KernSmooth   KernSmooth   /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
MASS         MASS         /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
Matrix       Matrix       /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
ModelMetrics ModelMetrics /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
R6           R6           /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
RColorBrewer RColorBrewer /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
Rcpp         Rcpp         /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
RcppRoll     RcppRoll     /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
SQUAREM      SQUAREM      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
TTR          TTR          /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
askpass      askpass      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
assertthat   assertthat   /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
backports    backports    /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
base         base         /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
base64enc    base64enc    /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
boot         boot         /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
broom        broom        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
callr        callr        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
caret        caret        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
cellranger   cellranger   /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
class        class        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
cli          cli          /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
clipr        clipr        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
cluster      cluster      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
codetools    codetools    /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
colorspace   colorspace   /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
...          ...          ...                                                  
shiny        shiny        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
sourcetools  sourcetools  /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
spatial      spatial      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
splines      splines      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
stats        stats        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
stats4       stats4       /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
stringi      stringi      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
stringr      stringr      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
survival     survival     /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
sys          sys          /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tcltk        tcltk        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tibble       tibble       /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tidyr        tidyr        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tidyselect   tidyselect   /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tidyverse    tidyverse    /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
timeDate     timeDate     /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tinytex      tinytex      /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
tools        tools        /Users/Manqi/opt/anaconda3/envs/PythonR/lib/R/library
utf8         

In [23]:
x <- 1:4
x > 2

[1] FALSE FALSE  TRUE  TRUE